#.bash_aliases
# Proxy
alias proxyfy='export http_proxy="http://10.0.0.254:3128/"'
alias unproxify='export http_proxy='

# Security aliases
#alias rm='rm -i'
#alias cp='cp -i' 
#alias mv='mv -i'

# ls aliases #For backward compatibility
alias d='ls -d */'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ls='ls --color=auto'
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'

# Divers:
alias cls='clear'
alias md='mkdir' 
alias rd='rmdir'
alias tracert='traceroute'
alias hexedit='hexedit --color'
alias vi='vim'
alias vid='vim -u ~/.vimrc-dev'
alias vip='vim -u ~/.vimrc-dev +Project'
[[ $(ps -ef |awk "\$2 == $(ps -ef | awk "\$2 == $$ {print \$3}") {print \$8}" |grep vi) ]]&& alias :q='exit' || alias :q='echo "Not in vi{m} !"';
alias sc='screen'
alias grep='grep --color=auto'
alias rgrep='rgrep --color=auto'
alias egrep='egrep --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cmd="echo $PATH | sed 's/:/\n/g' | xargs ls | column -c 1 | grep -v ':' | sort"
#alias showmod="lsmod | cut -d' ' -f1 | xargs modinfo | egrep '^file|^desc|^dep' | sed -e'/^dep/s/$/\n/g'"
alias showmod='modinfo $(cut -d" " -f1 /proc/modules) | sed "/^dep/s/$/\n/; /^file\|^desc\|^dep/!d"'
alias PS1="man bash | sed -n '/ASCII bell/,/end a sequence/p'"

#Pseudo OOP
alias alias.delete='unalias'
alias alias.edit='$EDITOR ~/.bash_aliases'
alias alias.list='alias'
alias alias.list.ters='alias |cut -d " " -f2- |cut -d "=" -f1'
alias alias.new='alias'
alias alias.reload='. ~/.bash_aliases'
alias alias.save='alias > ~/.bash_aliases'

alias dir.change='cd'
alias dir.contents='ls'
alias dir.contents.long='dir.contents -la'
alias dir.current='pwd'
alias dir.delete='rmdir'
alias dir.list='ls'
alias dir.list.help='ls --help'
alias dir.move='mv'
alias dir.new='mkdir'
alias dir.remove='rmdir'
alias dir.rename='mv'

alias file.cut='cut'
alias file.delete='rm'
alias file.head='head'
alias file.grep='grep'
alias file.join='join'
alias file.move='mv'
alias file.new='touch'
alias file.paste='paste'
alias file.properties='stat'
alias file.rename='rename'
alias file.sort='sort'
alias file.stat='stat'
alias file.tail='tail'
alias file.type='file'

alias function.delete='unset -f'
alias function.edit='$EDITOR ~/.bash_functions'
alias function.list.detailed='declare -f'
alias function.list.terse='declare -F | cut -d "=" -f2- |cut -d " " -f3'
alias function.new='function'
alias function.reload='. ~/.bash_functions'
alias function.save='echo "declare -f > ~/.bash_functions is not a good idea" '

alias user.delete='userdel'
alias user.id='id'
alias user.list='sort /etc/passwd'
alias user.me='whoami'
alias user.new='useradd'
alias user.properties='id'
alias user.stat='id'

alias var.delete='unset'
alias var.exported.list='declare -x'
alias var.list='set'
alias var.new='declare'

#apt
alias apt.autoclean='apt-get autoclean'
alias apt.autoremove='apt-get autoremove'
alias apt.builddep='apt-get build-dep'
alias apt.check='apt-get check'
alias apt.clean='apt-get clean'
alias apt.distupgrade='apt-get dist-upgrade'
alias apt.dselectupgrade='apt-get dselect-upgrade'
alias apt.install='apt-get install'
alias apt.purge='at-get purge'
alias apt.remove='apt-get remove'
alias apt.source='apt-get source'
alias apt.update='apt-get update'
alias apt.upgrade='apt-get upgrade'
alias apt.moo='apt-get moo'
#apt-cache
alias apt.add='apt-cache add'
alias apt.depends='apt-cache depends'
alias apt.dotty='apt-cache dotty'
alias apt.dump='apt-cache dump'
alias apt.dumpavail='apt-cache dumpavail'
alias apt.gencaches='apt-cache gencache'
alias apt.madison='apt-cache madison'
alias apt.pkgnames='apt-cache pkgname'
alias apt.policy='apt-cache policy'
alias apt.rdepends='apt-cache rdepends'
alias apt.search='apt-cache search'
alias apt.show='apt-cache show'
alias apt.showpkg='apt-cache showpkg'
alias apt.showsrc='apt-cache showsrc'
alias apt.stats='apt-cache stat'
alias apt.unmet='apt-cache unmet'
alias apt.xvcg='apt-cache xvcg'
#apt.file
alias apt.file.update='apt-file update'
alias apt.file.search='apt-file search'
alias apt.file.find='apt-file find'
alias apt.file.show='apt-file show'
alias apt.file.list='apt-file list'
alias apt.file.purge='apt-file purge'
#aptitude
alias aptitude.addusertag='aptitude add-user-tag' 
alias aptitude.autoclean='aptitude autoclean'
alias aptitude.builddep='aptitude builddep'
alias aptitude.changelog='aptitude changelog'
alias aptitude.clean='aptitude clean'
alias aptitude.distupgrade='aptitude dist-upgrade'
alias aptitude.download='aptitude download'
alias aptitude.forbidversion='aptitude forbid-version'
alias aptitude.forgetnew='aptitude forget-new'
alias aptitude.fullupgrade='aptitude full-upgrade'
alias aptitude.hold='aptitude hold'
alias aptitude.install='aptitude install'
alias aptitude.keepall='aptitude keep-all'
alias aptitude.markauto='aptitude markauto'
alias aptitude.purge='aptitude purge'
alias aptitude.reinstall='aptitude reinstall'
alias aptitude.remove='aptitude remove'
alias aptitude.remove-user-tag='aptitude remove-user-tag'
alias aptitude.safeupgrade='aptitude safe-upgrade'
alias aptitude.search='aptitude search'
alias aptitude.show='aptitude show'
alias aptitude.unhold='aptitude unhold'
alias aptitude.unmarkauto='aptitude unmarkauto'
alias aptitude.update='aptitude update'
alias aptitude.upgrade='aptitude upgrade'
alias aptitude.why='aptitude why'
alias aptitude.whynot='aptitude why-not'

##Saved Alias.
